import type { FieldPrototype, PropEditorsDefinition } from '../types'

const basicPropEditors: PropEditorsDefinition = {
  'v-model:value': {
    type: 'String',
    editor: 'expression',
    label: '绑定字段',
    group: 'basic',
    placeholder: '$state.formData.fieldName',
  },
  placeholder: {
    type: 'String',
    editor: 'string',
    label: '占位提示',
    group: 'basic',
    placeholder: '请输入...',
  },
  disabled: {
    type: 'Boolean',
    editor: 'boolean',
    label: '禁用',
    group: 'basic',
    default: false,
  },
  size: {
    type: 'String',
    editor: 'select',
    label: '尺寸',
    group: 'layout',
    options: [
      { label: '默认', value: 'middle' },
      { label: '大', value: 'large' },
      { label: '小', value: 'small' },
    ],
  },
  allowClear: {
    type: 'Boolean',
    editor: 'boolean',
    label: '允许清除',
    group: 'basic',
    default: false,
  },
}

const validationEditors: PropEditorsDefinition = {
  required: {
    type: 'Boolean',
    editor: 'boolean',
    label: '必填',
    group: 'validation',
    default: false,
  },
  rules: {
    type: 'Array',
    editor: 'json',
    label: '校验规则',
    group: 'validation',
    placeholder: '[]',
  },
}

export const defaultPrototypes: FieldPrototype[] = [
  {
    type: 'AForm',
    label: '表单',
    icon: '📋',
    category: 'layout',
    isContainer: true,
    locked: true,
    defaultProps: { layout: 'vertical' },
    propEditors: {
      layout: {
        type: 'String',
        editor: 'select',
        label: '布局方式',
        group: 'layout',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '内联', value: 'inline' },
        ],
      },
      labelCol: {
        type: 'Object',
        editor: 'json',
        label: '标签宽度',
        group: 'layout',
        placeholder: '{ span: 6 }',
      },
      wrapperCol: {
        type: 'Object',
        editor: 'json',
        label: '内容宽度',
        group: 'layout',
        placeholder: '{ span: 18 }',
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '组件尺寸',
        group: 'layout',
        options: [
          { label: '默认', value: 'middle' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
    },
  },
  {
    type: 'AFormItem',
    label: '表单项',
    icon: '📦',
    category: 'layout',
    isContainer: true,
    defaultProps: { label: '字段标签', name: '' },
    propEditors: {
      label: {
        type: 'String',
        editor: 'string',
        label: '标签文本',
        group: 'basic',
        placeholder: '字段标签',
      },
      name: {
        type: 'String',
        editor: 'string',
        label: '字段名',
        group: 'basic',
        placeholder: 'fieldName',
      },
      required: {
        type: 'Boolean',
        editor: 'boolean',
        label: '必填',
        group: 'validation',
        default: false,
      },
      rules: {
        type: 'Array',
        editor: 'json',
        label: '校验规则',
        group: 'validation',
        placeholder: '[]',
      },
      extra: {
        type: 'String',
        editor: 'string',
        label: '提示信息',
        group: 'basic',
        placeholder: '请输入...',
      },
      colon: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示冒号',
        group: 'layout',
        default: true,
      },
    },
  },
  {
    type: 'AInput',
    label: '输入框',
    icon: '✏️',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入' },
    propEditors: {
      ...basicPropEditors,
      maxlength: {
        type: 'Number',
        editor: 'number',
        label: '最大长度',
        group: 'basic',
      },
      showCount: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示字数',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AInputPassword',
    label: '密码框',
    icon: '🔒',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入密码' },
    propEditors: {
      ...basicPropEditors,
      visibilityToggle: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示切换按钮',
        group: 'basic',
        default: true,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATextArea',
    label: '文本域',
    icon: '📝',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入', rows: 4 },
    propEditors: {
      ...basicPropEditors,
      rows: {
        type: 'Number',
        editor: 'number',
        label: '行数',
        group: 'basic',
        default: 4,
      },
      maxlength: {
        type: 'Number',
        editor: 'number',
        label: '最大长度',
        group: 'basic',
      },
      showCount: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示字数',
        group: 'basic',
        default: false,
      },
      autoSize: {
        type: 'Boolean',
        editor: 'boolean',
        label: '自适应高度',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AInputNumber',
    label: '数字输入框',
    icon: '🔢',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入', style: 'width: 100%' },
    propEditors: {
      ...basicPropEditors,
      min: {
        type: 'Number',
        editor: 'number',
        label: '最小值',
        group: 'basic',
      },
      max: {
        type: 'Number',
        editor: 'number',
        label: '最大值',
        group: 'basic',
      },
      step: {
        type: 'Number',
        editor: 'number',
        label: '步长',
        group: 'basic',
        default: 1,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASelect',
    label: '下拉选择',
    icon: '🔽',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: { placeholder: '请选择', style: 'width: 100%' },
    propEditors: {
      ...basicPropEditors,
      mode: {
        type: 'String',
        editor: 'select',
        label: '模式',
        group: 'basic',
        options: [
          { label: '单选', value: undefined },
          { label: '多选', value: 'multiple' },
        ],
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      ...validationEditors,
    },
  },
  {
    type: 'ARadioGroup',
    label: '单选组',
    icon: '🔘',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: {},
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ACheckboxGroup',
    label: '多选组',
    icon: '☑️',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: {},
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASwitch',
    label: '开关',
    icon: '🔀',
    category: 'selection',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:checked': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      checkedChildren: {
        type: 'String',
        editor: 'string',
        label: '选中文案',
        group: 'basic',
        placeholder: '开',
      },
      unCheckedChildren: {
        type: 'String',
        editor: 'string',
        label: '未选文案',
        group: 'basic',
        placeholder: '关',
      },
    },
  },
  {
    type: 'ADatePicker',
    label: '日期选择',
    icon: '📅',
    category: 'date',
    wrapIn: 'AFormItem',
    defaultProps: { style: 'width: 100%' },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      placeholder: {
        type: 'String',
        editor: 'string',
        label: '占位提示',
        group: 'basic',
        placeholder: '请选择日期',
      },
      format: {
        type: 'String',
        editor: 'string',
        label: '日期格式',
        group: 'basic',
        placeholder: 'YYYY-MM-DD',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      allowClear: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许清除',
        group: 'basic',
        default: true,
      },
      showTime: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示时间',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATimePicker',
    label: '时间选择',
    icon: '⏰',
    category: 'date',
    wrapIn: 'AFormItem',
    defaultProps: { style: 'width: 100%' },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      placeholder: {
        type: 'String',
        editor: 'string',
        label: '占位提示',
        group: 'basic',
        placeholder: '请选择时间',
      },
      format: {
        type: 'String',
        editor: 'string',
        label: '时间格式',
        group: 'basic',
        placeholder: 'HH:mm:ss',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      allowClear: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许清除',
        group: 'basic',
        default: true,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ACascader',
    label: '级联选择',
    icon: '🌳',
    category: 'advanced',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请选择', style: 'width: 100%' },
    propEditors: {
      ...basicPropEditors,
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项", value: "1" }]',
      },
      multiple: {
        type: 'Boolean',
        editor: 'boolean',
        label: '多选',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AUpload',
    label: '上传',
    icon: '📤',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      action: {
        type: 'String',
        editor: 'string',
        label: '上传地址',
        group: 'basic',
        placeholder: '/api/upload',
      },
      name: {
        type: 'String',
        editor: 'string',
        label: '文件字段名',
        group: 'basic',
        placeholder: 'file',
      },
      multiple: {
        type: 'Boolean',
        editor: 'boolean',
        label: '多文件',
        group: 'basic',
        default: false,
      },
      accept: {
        type: 'String',
        editor: 'string',
        label: '文件类型',
        group: 'basic',
        placeholder: '.jpg,.png,.pdf',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ARate',
    label: '评分',
    icon: '⭐',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      count: {
        type: 'Number',
        editor: 'number',
        label: '总数',
        group: 'basic',
        default: 5,
      },
      allowHalf: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许半星',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASlider',
    label: '滑动条',
    icon: '🎚️',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      min: {
        type: 'Number',
        editor: 'number',
        label: '最小值',
        group: 'basic',
        default: 0,
      },
      max: {
        type: 'Number',
        editor: 'number',
        label: '最大值',
        group: 'basic',
        default: 100,
      },
      step: {
        type: 'Number',
        editor: 'number',
        label: '步长',
        group: 'basic',
        default: 1,
      },
      range: {
        type: 'Boolean',
        editor: 'boolean',
        label: '双滑块',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATransfer',
    label: '穿梭框',
    icon: '↔️',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:targetKeys': {
        type: 'String',
        editor: 'expression',
        label: '目标数据',
        group: 'basic',
        placeholder: '$state.formData.selected',
      },
      dataSource: {
        type: 'Array',
        editor: 'json',
        label: '数据源',
        group: 'basic',
        placeholder: '[{ key: "1", title: "选项1" }]',
      },
      titles: {
        type: 'Array',
        editor: 'json',
        label: '标题',
        group: 'basic',
        placeholder: '["源列表", "目标列表"]',
      },
      showSearch: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示搜索',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
    },
  },
]
