import type { FieldPrototype, PropEditorsDefinition } from '../types'

const basicPropEditors: PropEditorsDefinition = {
  'v-model:value': {
    type: 'String',
    editor: 'expression',
    label: '绑定字段',
    group: 'basic',
    placeholder: '$state.formData.fieldName',
  },
  placeholder: {
    type: 'String',
    editor: 'string',
    label: '占位提示',
    group: 'basic',
    placeholder: '请输入...',
  },
  disabled: {
    type: 'Boolean',
    editor: 'boolean',
    label: '禁用',
    group: 'basic',
    default: false,
  },
  size: {
    type: 'String',
    editor: 'select',
    label: '尺寸',
    group: 'layout',
    options: [
      { label: '默认', value: 'middle' },
      { label: '大', value: 'large' },
      { label: '小', value: 'small' },
    ],
  },
  allowClear: {
    type: 'Boolean',
    editor: 'boolean',
    label: '允许清除',
    group: 'basic',
    default: false,
  },
}

const validationEditors: PropEditorsDefinition = {
  required: {
    type: 'Boolean',
    editor: 'boolean',
    label: '必填',
    group: 'validation',
    default: false,
  },
  rules: {
    type: 'Array',
    editor: 'json',
    label: '校验规则',
    group: 'validation',
    placeholder: '[]',
  },
}

export const defaultPrototypes: FieldPrototype[] = [
  {
    type: 'AForm',
    label: '表单',
    icon: '📋',
    category: 'layout',
    isContainer: true,
    locked: true,
    defaultProps: { layout: 'vertical' },
    propEditors: {
      layout: {
        type: 'String',
        editor: 'select',
        label: '布局方式',
        group: 'layout',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '内联', value: 'inline' },
        ],
      },
      labelCol: {
        type: 'Object',
        editor: 'json',
        label: '标签宽度',
        group: 'layout',
        placeholder: '{ span: 6 }',
      },
      wrapperCol: {
        type: 'Object',
        editor: 'json',
        label: '内容宽度',
        group: 'layout',
        placeholder: '{ span: 18 }',
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '组件尺寸',
        group: 'layout',
        options: [
          { label: '默认', value: 'middle' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
    },
  },
  {
    type: 'AFormItem',
    label: '表单项',
    icon: '📦',
    category: 'layout',
    isContainer: true,
    defaultProps: { label: '字段标签', name: '' },
    propEditors: {
      label: {
        type: 'String',
        editor: 'string',
        label: '标签文本',
        group: 'basic',
        placeholder: '字段标签',
      },
      name: {
        type: 'String',
        editor: 'string',
        label: '字段名',
        group: 'basic',
        placeholder: 'fieldName',
      },
      required: {
        type: 'Boolean',
        editor: 'boolean',
        label: '必填',
        group: 'validation',
        default: false,
      },
      rules: {
        type: 'Array',
        editor: 'json',
        label: '校验规则',
        group: 'validation',
        placeholder: '[]',
      },
      extra: {
        type: 'String',
        editor: 'string',
        label: '提示信息',
        group: 'basic',
        placeholder: '请输入...',
      },
      colon: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示冒号',
        group: 'layout',
        default: true,
      },
    },
  },
  {
    type: 'AInput',
    label: '输入框',
    icon: '✏️',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入' },
    propEditors: {
      ...basicPropEditors,
      maxlength: {
        type: 'Number',
        editor: 'number',
        label: '最大长度',
        group: 'basic',
      },
      showCount: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示字数',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AInputPassword',
    label: '密码框',
    icon: '🔒',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入密码' },
    propEditors: {
      ...basicPropEditors,
      visibilityToggle: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示切换按钮',
        group: 'basic',
        default: true,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATextArea',
    label: '文本域',
    icon: '📝',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入', rows: 4 },
    propEditors: {
      ...basicPropEditors,
      rows: {
        type: 'Number',
        editor: 'number',
        label: '行数',
        group: 'basic',
        default: 4,
      },
      maxlength: {
        type: 'Number',
        editor: 'number',
        label: '最大长度',
        group: 'basic',
      },
      showCount: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示字数',
        group: 'basic',
        default: false,
      },
      autoSize: {
        type: 'Boolean',
        editor: 'boolean',
        label: '自适应高度',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AInputNumber',
    label: '数字输入框',
    icon: '🔢',
    category: 'basic',
    wrapIn: 'AFormItem',
    defaultProps: { placeholder: '请输入', style: 'width: 100%' },
    propEditors: {
      ...basicPropEditors,
      min: {
        type: 'Number',
        editor: 'number',
        label: '最小值',
        group: 'basic',
      },
      max: {
        type: 'Number',
        editor: 'number',
        label: '最大值',
        group: 'basic',
      },
      step: {
        type: 'Number',
        editor: 'number',
        label: '步长',
        group: 'basic',
        default: 1,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASelect',
    label: '下拉选择',
    icon: '🔽',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: {
      placeholder: '请选择',
      style: 'width: 100%',
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    propEditors: {
      ...basicPropEditors,
      mode: {
        type: 'String',
        editor: 'select',
        label: '模式',
        group: 'basic',
        options: [
          { label: '单选', value: undefined },
          { label: '多选', value: 'multiple' },
        ],
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      ...validationEditors,
    },
  },
  {
    type: 'ARadioGroup',
    label: '单选组',
    icon: '🔘',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: {
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ACheckboxGroup',
    label: '多选组',
    icon: '☑️',
    category: 'selection',
    wrapIn: 'AFormItem',
    isContainer: true,
    defaultProps: {
      options: [
        { label: '选项1', value: '1' },
        { label: '选项2', value: '2' },
        { label: '选项3', value: '3' },
      ],
    },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项1", value: "1" }]',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASwitch',
    label: '开关',
    icon: '🔀',
    category: 'selection',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:checked': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      checkedChildren: {
        type: 'String',
        editor: 'string',
        label: '选中文案',
        group: 'basic',
        placeholder: '开',
      },
      unCheckedChildren: {
        type: 'String',
        editor: 'string',
        label: '未选文案',
        group: 'basic',
        placeholder: '关',
      },
    },
  },
  {
    type: 'ADatePicker',
    label: '日期选择',
    icon: '📅',
    category: 'date',
    wrapIn: 'AFormItem',
    defaultProps: { style: 'width: 100%' },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      placeholder: {
        type: 'String',
        editor: 'string',
        label: '占位提示',
        group: 'basic',
        placeholder: '请选择日期',
      },
      format: {
        type: 'String',
        editor: 'string',
        label: '日期格式',
        group: 'basic',
        placeholder: 'YYYY-MM-DD',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      allowClear: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许清除',
        group: 'basic',
        default: true,
      },
      showTime: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示时间',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATimePicker',
    label: '时间选择',
    icon: '⏰',
    category: 'date',
    wrapIn: 'AFormItem',
    defaultProps: { style: 'width: 100%' },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      placeholder: {
        type: 'String',
        editor: 'string',
        label: '占位提示',
        group: 'basic',
        placeholder: '请选择时间',
      },
      format: {
        type: 'String',
        editor: 'string',
        label: '时间格式',
        group: 'basic',
        placeholder: 'HH:mm:ss',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      allowClear: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许清除',
        group: 'basic',
        default: true,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ACascader',
    label: '级联选择',
    icon: '🌳',
    category: 'advanced',
    wrapIn: 'AFormItem',
    defaultProps: {
      placeholder: '请选择',
      style: 'width: 100%',
      options: [
        { label: '选项1', value: '1', children: [{ label: '子选项1', value: '1-1' }] },
        { label: '选项2', value: '2', children: [{ label: '子选项2', value: '2-1' }] },
      ],
    },
    propEditors: {
      ...basicPropEditors,
      options: {
        type: 'Array',
        editor: 'json',
        label: '选项数据',
        group: 'basic',
        placeholder: '[{ label: "选项", value: "1" }]',
      },
      multiple: {
        type: 'Boolean',
        editor: 'boolean',
        label: '多选',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'AUpload',
    label: '上传',
    icon: '📤',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      action: {
        type: 'String',
        editor: 'string',
        label: '上传地址',
        group: 'basic',
        placeholder: '/api/upload',
      },
      name: {
        type: 'String',
        editor: 'string',
        label: '文件字段名',
        group: 'basic',
        placeholder: 'file',
      },
      multiple: {
        type: 'Boolean',
        editor: 'boolean',
        label: '多文件',
        group: 'basic',
        default: false,
      },
      accept: {
        type: 'String',
        editor: 'string',
        label: '文件类型',
        group: 'basic',
        placeholder: '.jpg,.png,.pdf',
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ARate',
    label: '评分',
    icon: '⭐',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      count: {
        type: 'Number',
        editor: 'number',
        label: '总数',
        group: 'basic',
        default: 5,
      },
      allowHalf: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许半星',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ASlider',
    label: '滑动条',
    icon: '🎚️',
    category: 'advanced',
    wrapIn: 'AFormItem',
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      min: {
        type: 'Number',
        editor: 'number',
        label: '最小值',
        group: 'basic',
        default: 0,
      },
      max: {
        type: 'Number',
        editor: 'number',
        label: '最大值',
        group: 'basic',
        default: 100,
      },
      step: {
        type: 'Number',
        editor: 'number',
        label: '步长',
        group: 'basic',
        default: 1,
      },
      range: {
        type: 'Boolean',
        editor: 'boolean',
        label: '双滑块',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATransfer',
    label: '穿梭框',
    icon: '↔️',
    category: 'advanced',
    wrapIn: 'AFormItem',
    defaultProps: {
      dataSource: [
        { key: '1', title: '选项1' },
        { key: '2', title: '选项2' },
        { key: '3', title: '选项3' },
      ],
      targetKeys: ['1'],
    },
    propEditors: {
      'v-model:targetKeys': {
        type: 'String',
        editor: 'expression',
        label: '目标数据',
        group: 'basic',
        placeholder: '$state.formData.selected',
      },
      dataSource: {
        type: 'Array',
        editor: 'json',
        label: '数据源',
        group: 'basic',
        placeholder: '[{ key: "1", title: "选项1" }]',
      },
      titles: {
        type: 'Array',
        editor: 'json',
        label: '标题',
        group: 'basic',
        placeholder: '["源列表", "目标列表"]',
      },
      showSearch: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示搜索',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ATable',
    label: '表格',
    icon: '📊',
    category: 'display',
    isContainer: false,
    defaultProps: {
      bordered: true,
      size: 'middle',
      columns: [
        { title: '列1', dataIndex: 'col1', key: 'col1' },
        { title: '列2', dataIndex: 'col2', key: 'col2' },
      ],
      dataSource: [{ key: '1', col1: '数据1', col2: '数据2' }],
    },
    propEditors: {
      columns: {
        type: 'Array',
        editor: 'json',
        label: '列配置',
        group: 'basic',
        placeholder: '[{ title: "列名", dataIndex: "field" }]',
      },
      dataSource: {
        type: 'Array',
        editor: 'expression',
        label: '数据源',
        group: 'basic',
        placeholder: '$state.tableData',
      },
      bordered: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示边框',
        group: 'basic',
        default: true,
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '表格大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'middle' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
      pagination: {
        type: 'Object',
        editor: 'json',
        label: '分页配置',
        group: 'basic',
        placeholder: '{ pageSize: 10 }',
      },
      rowKey: {
        type: 'String',
        editor: 'string',
        label: '行唯一键',
        group: 'basic',
        placeholder: 'id',
      },
    },
  },
  {
    type: 'AList',
    label: '列表',
    icon: '📑',
    category: 'display',
    isContainer: true,
    defaultProps: {
      bordered: false,
      split: true,
      dataSource: [
        { id: 1, title: '列表项1', description: '描述信息1' },
        { id: 2, title: '列表项2', description: '描述信息2' },
      ],
    },
    propEditors: {
      dataSource: {
        type: 'Array',
        editor: 'expression',
        label: '数据源',
        group: 'basic',
        placeholder: '$state.listData',
      },
      bordered: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示边框',
        group: 'basic',
        default: false,
      },
      split: {
        type: 'Boolean',
        editor: 'boolean',
        label: '分割线',
        group: 'basic',
        default: true,
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '列表大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
          { label: '大', value: 'large' },
        ],
      },
      grid: {
        type: 'Object',
        editor: 'json',
        label: '栅格配置',
        group: 'layout',
        placeholder: '{ gutter: 16, column: 4 }',
      },
    },
  },
  {
    type: 'ACard',
    label: '卡片',
    icon: '🃏',
    category: 'display',
    isContainer: true,
    defaultProps: { bordered: true },
    propEditors: {
      title: {
        type: 'String',
        editor: 'string',
        label: '标题',
        group: 'basic',
        placeholder: '卡片标题',
      },
      bordered: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示边框',
        group: 'basic',
        default: true,
      },
      hoverable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '悬浮效果',
        group: 'basic',
        default: false,
      },
      loading: {
        type: 'Boolean',
        editor: 'boolean',
        label: '加载状态',
        group: 'basic',
        default: false,
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '卡片大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
    },
  },
  {
    type: 'ADescriptions',
    label: '描述列表',
    icon: '📋',
    category: 'display',
    isContainer: false,
    defaultProps: { bordered: false, column: 3 },
    propEditors: {
      title: {
        type: 'String',
        editor: 'string',
        label: '标题',
        group: 'basic',
        placeholder: '描述列表标题',
      },
      bordered: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示边框',
        group: 'basic',
        default: false,
      },
      column: {
        type: 'Number',
        editor: 'number',
        label: '列数',
        group: 'layout',
        default: 3,
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
          { label: '大', value: 'large' },
        ],
      },
      layout: {
        type: 'String',
        editor: 'select',
        label: '布局',
        group: 'layout',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
    },
  },
  {
    type: 'AStatistic',
    label: '统计数值',
    icon: '📈',
    category: 'display',
    isContainer: false,
    defaultProps: {
      title: '统计标题',
      value: 1234,
    },
    propEditors: {
      title: {
        type: 'String',
        editor: 'string',
        label: '标题',
        group: 'basic',
        placeholder: '统计标题',
      },
      value: {
        type: 'Number',
        editor: 'expression',
        label: '数值',
        group: 'basic',
        placeholder: '$state.statValue',
      },
      suffix: {
        type: 'String',
        editor: 'string',
        label: '后缀',
        group: 'basic',
        placeholder: '个',
      },
      prefix: {
        type: 'String',
        editor: 'string',
        label: '前缀',
        group: 'basic',
        placeholder: '¥',
      },
      precision: {
        type: 'Number',
        editor: 'number',
        label: '精度',
        group: 'basic',
      },
    },
  },
  {
    type: 'ATree',
    label: '树形控件',
    icon: '🌲',
    category: 'display',
    isContainer: false,
    defaultProps: {
      showLine: false,
      treeData: [
        { title: '节点1', key: '1' },
        { title: '节点2', key: '2', children: [{ title: '子节点', key: '2-1' }] },
      ],
    },
    propEditors: {
      treeData: {
        type: 'Array',
        editor: 'json',
        label: '树形数据',
        group: 'basic',
        placeholder: '[{ title: "节点", key: "1", children: [] }]',
      },
      checkable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '可勾选',
        group: 'basic',
        default: false,
      },
      selectable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '可选中',
        group: 'basic',
        default: true,
      },
      showLine: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示连接线',
        group: 'basic',
        default: false,
      },
      defaultExpandAll: {
        type: 'Boolean',
        editor: 'boolean',
        label: '默认展开',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ATreeSelect',
    label: '树选择',
    icon: '🌳',
    category: 'display',
    wrapIn: 'AFormItem',
    defaultProps: {
      placeholder: '请选择',
      style: 'width: 100%',
      treeData: [
        { title: '选项1', value: '1' },
        { title: '选项2', value: '2', children: [{ title: '子选项', value: '2-1' }] },
      ],
    },
    propEditors: {
      'v-model:value': {
        type: 'String',
        editor: 'expression',
        label: '绑定字段',
        group: 'basic',
        placeholder: '$state.formData.fieldName',
      },
      treeData: {
        type: 'Array',
        editor: 'json',
        label: '树形数据',
        group: 'basic',
        placeholder: '[{ title: "节点", value: "1", children: [] }]',
      },
      placeholder: {
        type: 'String',
        editor: 'string',
        label: '占位提示',
        group: 'basic',
        placeholder: '请选择',
      },
      multiple: {
        type: 'Boolean',
        editor: 'boolean',
        label: '多选',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      allowClear: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许清除',
        group: 'basic',
        default: true,
      },
      showSearch: {
        type: 'Boolean',
        editor: 'boolean',
        label: '可搜索',
        group: 'basic',
        default: false,
      },
      ...validationEditors,
    },
  },
  {
    type: 'ATag',
    label: '标签',
    icon: '🏷️',
    category: 'display',
    isContainer: true,
    defaultProps: { color: 'blue' },
    propEditors: {
      color: {
        type: 'String',
        editor: 'select',
        label: '颜色',
        group: 'basic',
        options: [
          { label: '默认', value: 'default' },
          { label: '蓝色', value: 'blue' },
          { label: '绿色', value: 'green' },
          { label: '红色', value: 'red' },
          { label: '橙色', value: 'orange' },
          { label: '紫色', value: 'purple' },
          { label: '青色', value: 'cyan' },
          { label: '灰色', value: 'gray' },
        ],
      },
      closable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '可关闭',
        group: 'basic',
        default: false,
      },
      bordered: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示边框',
        group: 'basic',
        default: true,
      },
    },
  },
  {
    type: 'AAvatar',
    label: '头像',
    icon: '👤',
    category: 'display',
    isContainer: false,
    defaultProps: { size: 'default' },
    propEditors: {
      src: {
        type: 'String',
        editor: 'string',
        label: '图片地址',
        group: 'basic',
        placeholder: 'https://example.com/avatar.png',
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
      shape: {
        type: 'String',
        editor: 'select',
        label: '形状',
        group: 'layout',
        options: [
          { label: '圆形', value: 'circle' },
          { label: '方形', value: 'square' },
        ],
      },
      icon: {
        type: 'String',
        editor: 'string',
        label: '图标',
        group: 'basic',
        placeholder: 'user',
      },
    },
  },
  {
    type: 'AButton',
    label: '按钮',
    icon: '🔘',
    category: 'button',
    isContainer: true,
    defaultProps: { type: 'default' },
    propEditors: {
      type: {
        type: 'String',
        editor: 'select',
        label: '类型',
        group: 'basic',
        options: [
          { label: '默认', value: 'default' },
          { label: '主要', value: 'primary' },
          { label: '虚线', value: 'dashed' },
          { label: '文本', value: 'text' },
          { label: '链接', value: 'link' },
        ],
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'middle' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
      danger: {
        type: 'Boolean',
        editor: 'boolean',
        label: '危险按钮',
        group: 'basic',
        default: false,
      },
      disabled: {
        type: 'Boolean',
        editor: 'boolean',
        label: '禁用',
        group: 'basic',
        default: false,
      },
      loading: {
        type: 'Boolean',
        editor: 'boolean',
        label: '加载状态',
        group: 'basic',
        default: false,
      },
      block: {
        type: 'Boolean',
        editor: 'boolean',
        label: '宽度撑满',
        group: 'layout',
        default: false,
      },
      ghost: {
        type: 'Boolean',
        editor: 'boolean',
        label: '幽灵按钮',
        group: 'basic',
        default: false,
      },
      href: {
        type: 'String',
        editor: 'string',
        label: '链接地址',
        group: 'basic',
        placeholder: 'https://...',
      },
    },
  },
  {
    type: 'AButtonGroup',
    label: '按钮组',
    icon: '🖇️',
    category: 'button',
    isContainer: true,
    defaultProps: {},
    propEditors: {
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'middle' },
          { label: '大', value: 'large' },
          { label: '小', value: 'small' },
        ],
      },
    },
  },
  {
    type: 'ATabs',
    label: '标签页',
    icon: '📑',
    category: 'navigation',
    isContainer: true,
    defaultProps: { type: 'line' },
    propEditors: {
      'v-model:activeKey': {
        type: 'String',
        editor: 'expression',
        label: '当前激活',
        group: 'basic',
        placeholder: '$state.activeTab',
      },
      type: {
        type: 'String',
        editor: 'select',
        label: '样式类型',
        group: 'basic',
        options: [
          { label: '线条', value: 'line' },
          { label: '卡片', value: 'card' },
          { label: '可编辑卡片', value: 'editable-card' },
        ],
      },
      tabPosition: {
        type: 'String',
        editor: 'select',
        label: '位置',
        group: 'layout',
        options: [
          { label: '顶部', value: 'top' },
          { label: '右侧', value: 'right' },
          { label: '底部', value: 'bottom' },
          { label: '左侧', value: 'left' },
        ],
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
          { label: '大', value: 'large' },
        ],
      },
      animated: {
        type: 'Boolean',
        editor: 'boolean',
        label: '动画切换',
        group: 'basic',
        default: true,
      },
    },
  },
  {
    type: 'ABreadcrumb',
    label: '面包屑',
    icon: '🥖',
    category: 'navigation',
    isContainer: true,
    defaultProps: {},
    propEditors: {
      separator: {
        type: 'String',
        editor: 'string',
        label: '分隔符',
        group: 'basic',
        placeholder: '/',
      },
    },
  },
  {
    type: 'APagination',
    label: '分页',
    icon: '📄',
    category: 'navigation',
    isContainer: false,
    defaultProps: { pageSize: 10, total: 0 },
    propEditors: {
      current: {
        type: 'Number',
        editor: 'expression',
        label: '当前页',
        group: 'basic',
        placeholder: '$state.currentPage',
      },
      total: {
        type: 'Number',
        editor: 'expression',
        label: '总条数',
        group: 'basic',
        placeholder: '$state.total',
      },
      pageSize: {
        type: 'Number',
        editor: 'number',
        label: '每页条数',
        group: 'basic',
        default: 10,
      },
      showSizeChanger: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示条数切换',
        group: 'basic',
        default: false,
      },
      showQuickJumper: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示快速跳转',
        group: 'basic',
        default: false,
      },
      showTotal: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示总数',
        group: 'basic',
        default: false,
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
    },
  },
  {
    type: 'ASteps',
    label: '步骤条',
    icon: '👣',
    category: 'navigation',
    isContainer: false,
    defaultProps: { current: 0 },
    propEditors: {
      current: {
        type: 'Number',
        editor: 'expression',
        label: '当前步骤',
        group: 'basic',
        placeholder: '$state.currentStep',
      },
      direction: {
        type: 'String',
        editor: 'select',
        label: '方向',
        group: 'layout',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      status: {
        type: 'String',
        editor: 'select',
        label: '当前状态',
        group: 'basic',
        options: [
          { label: '等待', value: 'wait' },
          { label: '进行', value: 'process' },
          { label: '完成', value: 'finish' },
          { label: '错误', value: 'error' },
        ],
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
        ],
      },
      type: {
        type: 'String',
        editor: 'select',
        label: '类型',
        group: 'basic',
        options: [
          { label: '默认', value: 'default' },
          { label: '导航', value: 'navigation' },
        ],
      },
    },
  },
  {
    type: 'AMenu',
    label: '菜单',
    icon: '☰',
    category: 'navigation',
    isContainer: true,
    defaultProps: { mode: 'inline' },
    propEditors: {
      mode: {
        type: 'String',
        editor: 'select',
        label: '模式',
        group: 'basic',
        options: [
          { label: '内嵌', value: 'inline' },
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
        ],
      },
      theme: {
        type: 'String',
        editor: 'select',
        label: '主题',
        group: 'basic',
        options: [
          { label: '浅色', value: 'light' },
          { label: '深色', value: 'dark' },
        ],
      },
      inlineCollapsed: {
        type: 'Boolean',
        editor: 'boolean',
        label: '折叠',
        group: 'basic',
        default: false,
      },
      selectable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '允许选中',
        group: 'basic',
        default: true,
      },
    },
  },
  {
    type: 'AAlert',
    label: '警告提示',
    icon: '⚠️',
    category: 'feedback',
    isContainer: false,
    defaultProps: { type: 'info', showIcon: true },
    propEditors: {
      message: {
        type: 'String',
        editor: 'string',
        label: '主要提示',
        group: 'basic',
        placeholder: '提示内容',
      },
      description: {
        type: 'String',
        editor: 'string',
        label: '辅助提示',
        group: 'basic',
        placeholder: '详细描述',
      },
      type: {
        type: 'String',
        editor: 'select',
        label: '类型',
        group: 'basic',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
        ],
      },
      showIcon: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示图标',
        group: 'basic',
        default: true,
      },
      closable: {
        type: 'Boolean',
        editor: 'boolean',
        label: '可关闭',
        group: 'basic',
        default: false,
      },
      banner: {
        type: 'Boolean',
        editor: 'boolean',
        label: '顶部公告',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'AProgress',
    label: '进度条',
    icon: '📊',
    category: 'feedback',
    isContainer: false,
    defaultProps: { type: 'line', percent: 0 },
    propEditors: {
      percent: {
        type: 'Number',
        editor: 'expression',
        label: '百分比',
        group: 'basic',
        placeholder: '$state.progress',
      },
      type: {
        type: 'String',
        editor: 'select',
        label: '类型',
        group: 'basic',
        options: [
          { label: '线性', value: 'line' },
          { label: '圆形', value: 'circle' },
          { label: '仪表盘', value: 'dashboard' },
        ],
      },
      status: {
        type: 'String',
        editor: 'select',
        label: '状态',
        group: 'basic',
        options: [
          { label: '默认', value: 'normal' },
          { label: '成功', value: 'success' },
          { label: '异常', value: 'exception' },
          { label: '激活', value: 'active' },
        ],
      },
      showInfo: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示信息',
        group: 'basic',
        default: true,
      },
      strokeColor: {
        type: 'String',
        editor: 'string',
        label: '进度条颜色',
        group: 'style',
        placeholder: '#1890ff',
      },
      strokeWidth: {
        type: 'Number',
        editor: 'number',
        label: '线条宽度',
        group: 'layout',
      },
    },
  },
  {
    type: 'ASpin',
    label: '加载中',
    icon: '⏳',
    category: 'feedback',
    isContainer: true,
    defaultProps: { spinning: true },
    propEditors: {
      spinning: {
        type: 'Boolean',
        editor: 'expression',
        label: '加载状态',
        group: 'basic',
        placeholder: '$state.loading',
      },
      size: {
        type: 'String',
        editor: 'select',
        label: '大小',
        group: 'layout',
        options: [
          { label: '默认', value: 'default' },
          { label: '小', value: 'small' },
          { label: '大', value: 'large' },
        ],
      },
      tip: {
        type: 'String',
        editor: 'string',
        label: '提示文案',
        group: 'basic',
        placeholder: '加载中...',
      },
      delay: {
        type: 'Number',
        editor: 'number',
        label: '延迟显示',
        group: 'basic',
      },
    },
  },
  {
    type: 'ASkeleton',
    label: '骨架屏',
    icon: '🦴',
    category: 'feedback',
    isContainer: false,
    defaultProps: { active: true },
    propEditors: {
      active: {
        type: 'Boolean',
        editor: 'boolean',
        label: '动画效果',
        group: 'basic',
        default: true,
      },
      loading: {
        type: 'Boolean',
        editor: 'expression',
        label: '加载状态',
        group: 'basic',
        placeholder: '$state.loading',
      },
      avatar: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示头像',
        group: 'basic',
        default: false,
      },
      paragraph: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示段落',
        group: 'basic',
        default: true,
      },
      title: {
        type: 'Boolean',
        editor: 'boolean',
        label: '显示标题',
        group: 'basic',
        default: true,
      },
      round: {
        type: 'Boolean',
        editor: 'boolean',
        label: '圆角样式',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'AResult',
    label: '结果页',
    icon: '✅',
    category: 'feedback',
    isContainer: true,
    defaultProps: { status: 'info' },
    propEditors: {
      status: {
        type: 'String',
        editor: 'select',
        label: '状态',
        group: 'basic',
        options: [
          { label: '信息', value: 'info' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '错误', value: 'error' },
          { label: '403', value: '403' },
          { label: '404', value: '404' },
          { label: '500', value: '500' },
        ],
      },
      title: {
        type: 'String',
        editor: 'string',
        label: '标题',
        group: 'basic',
        placeholder: '操作成功',
      },
      subTitle: {
        type: 'String',
        editor: 'string',
        label: '副标题',
        group: 'basic',
        placeholder: '请继续下一步操作',
      },
    },
  },
  {
    type: 'ARow',
    label: '行容器',
    icon: '↔️',
    category: 'layout',
    isContainer: true,
    defaultProps: { gutter: 16 },
    propEditors: {
      gutter: {
        type: 'Number',
        editor: 'number',
        label: '栅格间隔',
        group: 'layout',
        default: 16,
      },
      type: {
        type: 'String',
        editor: 'select',
        label: '布局模式',
        group: 'layout',
        options: [
          { label: 'Flex', value: 'flex' },
        ],
      },
      justify: {
        type: 'String',
        editor: 'select',
        label: '水平排列',
        group: 'layout',
        options: [
          { label: '默认', value: 'start' },
          { label: '居中', value: 'center' },
          { label: '结束', value: 'end' },
          { label: '间隔', value: 'space-around' },
          { label: '两端', value: 'space-between' },
        ],
      },
      align: {
        type: 'String',
        editor: 'select',
        label: '垂直排列',
        group: 'layout',
        options: [
          { label: '顶部', value: 'top' },
          { label: '居中', value: 'middle' },
          { label: '底部', value: 'bottom' },
        ],
      },
      wrap: {
        type: 'Boolean',
        editor: 'boolean',
        label: '自动换行',
        group: 'layout',
        default: true,
      },
    },
  },
  {
    type: 'ACol',
    label: '列容器',
    icon: '↕️',
    category: 'layout',
    isContainer: true,
    defaultProps: { span: 12 },
    propEditors: {
      span: {
        type: 'Number',
        editor: 'number',
        label: '栅格占位',
        group: 'layout',
        default: 12,
        help: '0-24，总栅格数为24',
      },
      offset: {
        type: 'Number',
        editor: 'number',
        label: '左侧偏移',
        group: 'layout',
      },
      push: {
        type: 'Number',
        editor: 'number',
        label: '向右移动',
        group: 'layout',
      },
      pull: {
        type: 'Number',
        editor: 'number',
        label: '向左移动',
        group: 'layout',
      },
      xs: {
        type: 'Number',
        editor: 'number',
        label: '超小屏',
        group: 'layout',
        help: '<576px',
      },
      sm: {
        type: 'Number',
        editor: 'number',
        label: '小屏',
        group: 'layout',
        help: '≥576px',
      },
      md: {
        type: 'Number',
        editor: 'number',
        label: '中屏',
        group: 'layout',
        help: '≥768px',
      },
      lg: {
        type: 'Number',
        editor: 'number',
        label: '大屏',
        group: 'layout',
        help: '≥992px',
      },
      xl: {
        type: 'Number',
        editor: 'number',
        label: '超大屏',
        group: 'layout',
        help: '≥1200px',
      },
      xxl: {
        type: 'Number',
        editor: 'number',
        label: '特超大屏',
        group: 'layout',
        help: '≥1600px',
      },
    },
  },
  {
    type: 'ADivider',
    label: '分割线',
    icon: '➖',
    category: 'layout',
    isContainer: false,
    defaultProps: {},
    propEditors: {
      type: {
        type: 'String',
        editor: 'select',
        label: '类型',
        group: 'basic',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      dashed: {
        type: 'Boolean',
        editor: 'boolean',
        label: '虚线',
        group: 'basic',
        default: false,
      },
      orientation: {
        type: 'String',
        editor: 'select',
        label: '文字位置',
        group: 'layout',
        options: [
          { label: '居中', value: 'center' },
          { label: '左侧', value: 'left' },
          { label: '右侧', value: 'right' },
        ],
      },
      plain: {
        type: 'Boolean',
        editor: 'boolean',
        label: '文字普通样式',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ASpace',
    label: '间距',
    icon: '⬜',
    category: 'layout',
    isContainer: true,
    defaultProps: { size: 'small' },
    propEditors: {
      size: {
        type: 'String',
        editor: 'select',
        label: '间距大小',
        group: 'layout',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'middle' },
          { label: '大', value: 'large' },
        ],
      },
      direction: {
        type: 'String',
        editor: 'select',
        label: '排列方向',
        group: 'layout',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
      },
      align: {
        type: 'String',
        editor: 'select',
        label: '对齐方式',
        group: 'layout',
        options: [
          { label: '默认', value: 'start' },
          { label: '居中', value: 'center' },
          { label: '底部', value: 'end' },
          { label: '基线', value: 'baseline' },
        ],
      },
      wrap: {
        type: 'Boolean',
        editor: 'boolean',
        label: '自动换行',
        group: 'layout',
        default: false,
      },
      split: {
        type: 'Boolean',
        editor: 'boolean',
        label: '添加分割线',
        group: 'basic',
        default: false,
      },
    },
  },
  {
    type: 'ALayout',
    label: '布局容器',
    icon: '📐',
    category: 'layout',
    isContainer: true,
    locked: true,
    defaultProps: {},
    propEditors: {
      hasSider: {
        type: 'Boolean',
        editor: 'boolean',
        label: '包含侧边栏',
        group: 'layout',
        default: false,
      },
    },
  },
]
