import { createApp } from 'vue'
import App from './App.vue'
import 'ant-design-vue/dist/reset.css'
import * as Antd from 'ant-design-vue'

const app = createApp(App)

app.component('AForm', Antd.Form)
app.component('AFormItem', Antd.FormItem)
app.component('AInput', Antd.Input)
app.component('AInputPassword', Antd.Input.Password)
app.component('ATextArea', Antd.Input.TextArea)
app.component('AInputNumber', Antd.InputNumber)
app.component('ASelect', Antd.Select)
app.component('ASelectOption', Antd.SelectOption)
app.component('ASwitch', Antd.Switch)
app.component('ADatePicker', Antd.DatePicker)
app.component('ATimePicker', Antd.TimePicker)
app.component('ARadio', Antd.Radio)
app.component('ARadioGroup', Antd.Radio.Group)
app.component('ACheckbox', Antd.Checkbox)
app.component('ACheckboxGroup', Antd.Checkbox.Group)
app.component('ACascader', Antd.Cascader)
app.component('AUpload', Antd.Upload)
app.component('ARate', Antd.Rate)
app.component('ASlider', Antd.Slider)
app.component('ATransfer', Antd.Transfer)
app.component('ATree', Antd.Tree)
app.component('ATreeNode', Antd.TreeNode)
app.component('ATreeSelect', Antd.TreeSelect)
app.component('ATreeSelectNode', Antd.TreeSelectNode)
app.component('AList', Antd.List)
app.component('AListItem', Antd.List.Item)
app.component('AListItemMeta', Antd.List.Item.Meta)
app.component('ADescriptions', Antd.Descriptions)
app.component('ADescriptionsItem', Antd.Descriptions.Item)
app.component('AStatistic', Antd.Statistic)
app.component('ATag', Antd.Tag)
app.component('ABadge', Antd.Badge)
app.component('AAvatar', Antd.Avatar)
app.component('AButton', Antd.Button)
app.component('AButtonGroup', Antd.Button.Group)
app.component('AModal', Antd.Modal)
app.component('ADrawer', Antd.Drawer)
app.component('ASpin', Antd.Spin)
app.component('ASkeleton', Antd.Skeleton)
app.component('ACard', Antd.Card)
app.component('ATabs', Antd.Tabs)
app.component('ATabPane', Antd.Tabs.TabPane)
app.component('ABreadcrumb', Antd.Breadcrumb)
app.component('ABreadcrumbItem', Antd.Breadcrumb.Item)
app.component('APagination', Antd.Pagination)
app.component('ASteps', Antd.Steps)
app.component('AStep', Antd.Steps.Step)
app.component('AMenu', Antd.Menu)
app.component('AMenuItem', Antd.Menu.Item)
app.component('ASubMenu', Antd.Menu.SubMenu)
app.component('AAlert', Antd.Alert)
app.component('AProgress', Antd.Progress)
app.component('AResult', Antd.Result)
app.component('ATable', Antd.Table)
app.component('ATimeline', Antd.Timeline)
app.component('ATimelineItem', Antd.Timeline.Item)
app.component('ARow', Antd.Row)
app.component('ACol', Antd.Col)
app.component('ALayout', Antd.Layout)
app.component('ALayoutHeader', Antd.Layout.Header)
app.component('ALayoutFooter', Antd.Layout.Footer)
app.component('ALayoutSider', Antd.Layout.Sider)
app.component('ALayoutContent', Antd.Layout.Content)
app.component('ASpace', Antd.Space)
app.component('ADivider', Antd.Divider)
app.component('AAutoComplete', Antd.AutoComplete)
app.component('AMentions', Antd.Mentions)

app.mount('#app')
