export type { VueJsonSchema, VueJsonSchemaInput, ParsedSchema } from './schema';
export type {
  ExpressionValue,
  FunctionValue,
  StateRef,
  PropsRef,
  ScopeRef,
  LiteralValue,
  PropertyValue,
  InitialValue,
  ValueType,
  PropDefinition,
  PropsDefinition,
  EmitDefinition,
  EmitsDefinition,
  StateItemDefinition,
  StateDefinition,
  ComputedItemDefinition,
  ComputedDefinition,
  MethodsDefinition,
  WatchItemDefinition,
  WatchDefinition,
  ProvideItemDefinition,
  ProvideDefinition,
  InjectItemDefinition,
  InjectDefinition,
  LifecycleHookName,
  LifecycleDefinition,
  LocalComponentDefinition,
  AsyncComponentDefinition,
  ComponentDefinition,
  ComponentsDefinition,
  VNodeDirectives,
  VNodeChild,
  VNodeChildren,
  VNodeDefinition,
  TemplateRenderDefinition,
  FunctionRenderDefinition,
  RenderDefinition,
  StylesDefinition,
  ExpressionInput,
  StateInput,
  PropsInput,
  ScopeInput,
  FunctionInput,
  StructuredInput,
} from './schema';
export type {
  ExpressionParseData,
  VariableParseData,
  ScopeParseData,
  FunctionParseData,
  NestedReferenceResult,
} from './schema';
export type {
  ParserContext,
  ParseError,
  ParseWarning,
  RenderContext,
  SetupContext,
  ComponentFactoryOptions,
  ParseResult,
  CreateComponentOptions,
  UseVueJsonOptions,
} from './runtime';
